### ISSUE TITLE
Type inference failed. Expected type mismatch: inferred type is Boolean? but Boolean was expected

### ISSUE THREAD

**Issue by sandeepcmsm** [BaseflowIT/flutter-google-api-availability#5]
## 🐛 Bug Report

kotlin_version = '1.2.30'

Launching lib/main.dev.dart on ONEPLUS A6000 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDevDebug'...
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/sandeeepcmsm/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1+2/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/sandeeepcmsm/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1+2/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: /Users/sandeeepcmsm/.pub-cache/hosted/pub.dartlang.org/google_api_availability-1.0.2/android/src/main/kotlin/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.kt: (29, 48): Type inference failed. Expected type mismatch: inferred type is Boolean? but Boolean was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':google_api_availability:compileDebugKotlin'.
> Compilation error. See log for more details

### Configuration
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.9.7-pre.35, on Mac OS X 10.14 18A391, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.1.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.27.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
**Version:** 1.x

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@sandeepcmsm thank you for reporting this issue, I am on it.

**Comment by sandeepcmsm** [comment]
@mvanbeusekom I have reset my flutter repo to v0.8.6. its working fine there. may be flutter team had changed the MethodCall type.

**Comment by mvanbeusekom** [comment]
@sandeepcmsm that is exactly what happend ;) Flutter changed arguments from non-nullable boolean to nullable boolean (most likely in version 0.9.6). I have a fix ready and will release a new version of the plugin today.

**Comment by sandeepcmsm** [comment]
@mvanbeusekom thank you.
