### ISSUE TITLE
Upgrade Kotlin version

### ISSUE THREAD

**Issue by yvanvds** [BaseflowIT/flutter-google-api-availability#9]
## 🐛 Bug Report

I can't upgrade the latest Gradle plugin version to (>3.2.0) because of this plugin. Which in turn leaves me unable to use the new app format (Android App Bundle). This is because this plugin expects kotlin plugin to be at version 1.2.71. For the new Gradle plugin the kotlin version must be at least 1.3.0.

### Expected behavior
the app should compile
### Reproduction steps
add this plugin (or for instance geolocator, which has this as a dependency) and allow Android Studio to upgrade to the latest Gradle. 
### Configuration
Android studio version 3.3 on windows, flutter updated to latest version

**Version:** 1.0.4

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android

**Comment by khmak3** [comment]
This is necessaory with work with firebase cloud database GA version

**Comment by HengJunXi** [comment]
I also faced this issue. Is there any update on the problem?

**Comment by mvanbeusekom** [comment]
@HengJunXi since version 2.0 of this plugin we moved from using Kotlin to JAVA (and also updated to the latest Gradle version). Maybe you should give this a try.
